### ISSUE TITLE
For users who uses python3, this issue will solve your problem. 

### ISSUE THREAD

**Issue by HaujetZhao** [bbc/audio-offset-finder#13]
This repo is written for python2.7. 

Professor [Abram Hindle](https://github.com/abramhindle) have made a fork [audio-offset-finder](https://github.com/abramhindle/audio-offset-finder) and reimplemented it with python3, so you can check on it. It works very well.

**Comment by stephenjolly** [comment]
The relevant changes that @abramhindle made have now been integrated into this base repository.  Users may wish to check out his fork for other features that have not yet been implemented in this version however, including the addition of additional audio features in the comparison process that may make his version perform better on music.
