### ISSUE TITLE
when can i use it with python 3.9?

### ISSUE THREAD

**Issue by nakedou** [bbc/audio-offset-finder#15]

**Comment by stephenjolly** [comment]
It should work fine with Python 3.9 - what issues are you seeing?

It won't work with Python 3.10 yet, as tracked in #20.

**Comment by chrisn** [comment]
I just tried Python 3.9 and got this error when installing:

> error: numpy 1.22.3 is installed but numpy<1.22,>=1.18 is required by {'numba'}

As a workaround, I changed setup.py to set the numpy version like this:

```
'numpy>=1.21.0,<1.22.0'
```

**Comment by stephenjolly** [comment]
The current code builds and tests successfully with Python 3.9 under CI: https://github.com/bbc/audio-offset-finder/runs/6294212113?check_suite_focus=true.

Recent changes seem to have fixed the problems that @chrisn was having.

@nakedou - could you check and see if you're still having issues?
