### ISSUE TITLE
Possible error: encountered in double_scalars

### ISSUE THREAD

**Issue by olafthiele** [bbc/audio-offset-finder#34]
Trying to find a wave in a larger wave file, but encounter the following. Any idea why?

> /audio_offset_finder.py:149: RuntimeWarning: invalid value encountered in double_scalars
>   score = (c[max_k_index] - np.mean(c)) / np.std(c)  # standard score of peak
> Offset: 0.0 (seconds)
> Standard score: nan
>

**Comment by stephenjolly** [comment]
It looks like the calculated width of the correlation peak is zero, which is causing a divide-by-zero error.  A couple of things you could try:
- Check the input files to make sure they are valid audio files (I'm not sure what would happen if you tried looking for an offset between two files consisting only of silence, for example).
- Run the tool with the `--show-plot` option and check that it looks like the example referenced from `README.md`.

In the meantime, I'll look into updating the tool to provide more helpful output when this happens.

**Comment by olafthiele** [comment]
Thanks for looking into it. We are trying to locate a stinger audio of 4 sec lenght in 2 min audio.

- Both audios are valid wavs and playable, but there is someone speaking on top of the stinger.
- Thanks, didn't realise there was that option ...  `--help`

Your patch works if I import `math.inf`, but that is probably part of a larger PR. We'll check some more audios.

Closing this as it is our audios and not the offset finder.
