### ISSUE TITLE
Approach when it is unclear, which audio file of two is within the other one

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [bbc/audio-offset-finder#7]
I have two audio recordings of the same scene, but I don't know which one is "in" the other. Which approach is useful here to not only get the seconds of offset but also choose the right one automatically?

So far, I am testing both variations. If seconds is roughly the duration of the file, it's the other way round. Sometimes I also get 0 instead of the whole duration. Sometimes either is wrong.

**Comment by stephenjolly** [comment]
I suggest you run the tool twice, looking for one recording in the other, and then vice-versa.  The result with the highest standard score (reported as "Score" by the tool) is more likely to be the correct one.
