### ISSUE TITLE
How do I adapt the code to arbitrary lengths?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [bbc/audio-offset-finder#8]
I usually get no result with files shorter than about 30 seconds. How do I adapt the code to arbitrary lengths?

**Comment by stephenjolly** [comment]
This should now be fixed - the code now works down to very short audio file lengths, as of commit https://github.com/bbc/audio-offset-finder/commit/087d805b457b8e833677b6fbff5d4702678a83bc
